### ISSUE TITLE
Remove fixed height from session meta div

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/schedule-app-core#196] opened 2016-05-02 16:16 UTC
Session info appears to be in a fixed height box. A two-line title causes info to be cut off. 

<img width="393" alt="screenshot 2016-05-02 12 14 51" src="https://cloud.githubusercontent.com/assets/53411/14959880/a93e361c-105f-11e6-94e9-cd66b5770682.png">

**Comment by mmmavis** [comment] 2016-08-30 18:22
Can't reproduce this. It has probably been fixed along the way already. Closing this ticket now but feel free to reopen it if same bug occurs again.

**Closed by mmmavis** 2016-08-30 18:22 UTC
Labels: bug, Connecting Leaders, Development
